spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
  main:
    allow-circular-references: true

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
    title: Spring-Next-Docs
    description: Spring Boot REST API

logging:
  level:
    "[org.springframework.security]": TRACE
